name: geo_weather
description: "GeoWeather is a lightweight Flutter app that auto-detects your location and displays real-time weather conditions with a clean, simple interface."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Networking
  dio: ^5.9.0
  
  # State Management
  get: ^4.7.2
  
  # Functional Programming
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  # Environment Configuration
  envied: ^1.3.1
  
  # Connectivity
  connectivity_plus: ^6.0.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  
  # Location Services
  geolocator: ^10.1.0
  permission_handler: ^12.0.1
  
  # Shimmer Effect
  shimmer: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  envied_generator: ^1.3.1
  mockito: ^5.5.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
